
app.name=Library System

db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}

hikari.max.pool.size=10
hikari.min.idle=5
hikari.connection.timeout=30000
hikari.idle.timeout=600000
hikari.max.lifetime=1800000
