
app.name=Library System
app.books.file=books.json
app.members.file=members.json
app.loans.file=loans.json

db.url=jdbc:postgresql://localhost:5433/librarydb
db.username=postgres
db.password=postgres

hikari.max.pool.size=10
hikari.min.idle=5
hikari.connection.timeout=30000
hikari.idle.timeout=600000
hikari.max.lifetime=1800000
